### ISSUE TITLE
Torrents on deluge not working

### ISSUE THREAD

**Issue by TheOriginalXman** [Kabe0/deluge-windscribe#30]
I was able to do a clean install of the docker image with on the 'locale' error, However whenever I add in a torrent I sporadically get a few KB/s dl and then nothing. I have tried to dl the same torrent on another pc with deluge installed on a ubuntu vm and wind scribe on in my Mac and have no issues get a steady 1.5-2 MB/s. 

Any reason why this would be occurring in the docker image?

**Comment by Kabe0** [comment]
I found this was often caused by Deluge not looking at the multiple trackers. Sometimes the windscribe firewall can have issues with one of them. The solution that has worked for me is as follows...

Download itconfig
https://github.com/ratanakvlun/deluge-ltconfig/releases

Install in deluge by adding _ltConfig-2.0.0.egg_ to the config folder under _/.config/deluge/plugins_ which should be mounted to your container....
![image](https://user-images.githubusercontent.com/6827834/137574734-fa61c3a5-a71d-40a0-9337-56a00faa6feb.png)

Enable these two flags to allow Deluge to check all trackers
![image](https://user-images.githubusercontent.com/6827834/137574846-6854521d-7949-406b-a6bc-0cae227425dd.png)

**Comment by TheOriginalXman** [comment]
Thanks that did it!
